#!/usr/bin/env node

import promptly from 'promptly';

const description = 'Answer "yes" if the number is even, otherwise answer "no".';

const getRandomNum = (min = 0, max = 100) =>
 Math.floor(Math.random() * ((max - min) + 1)) + min;

const isEven = num => num % 2 === 0;

const generateData = () => {
  const question = getRandomNum();
  const answer = isEven(question) ? 'yes' : 'no';

   return [question, answer];
 };

const startGame = async (description, generateData) => {
  console.log('Welcome to the Brain Games!');

  const name = await promptly.prompt('May I have your name? ');
  console.log(`Hello, ${name}!`);
  console.log(`${description}`);

  for (let i = 0; i < 3; i += 1) {
    const gameData = generateData();
    const [question, answer] = gameData;

    console.log(`Question: ${question}`);
    const userAnswer = await promptly.prompt('Your answer: ');

   if (userAnswer === answer) {
      console.log('Correct!');
    } else {
      console.log(`"${userAnswer}" is wrong answer ;(. Correct answer was "${answer}".\nLet's try again, ${name}!`);
      return;
    }
  }

  console.log(`Congratulations, ${name}!`);
};

startGame(description, generateData);
